#!/bin/sh

# get workspace name

NAME=$(
  swaymsg -t get_workspaces | jq '.[] | select(.focused==true) | .name' |
  cut -d '"' -f2
)

NUMBER=$(echo $NAME | cut -d ':' -f1)

if [ "$NUMBER" = "10" ]; then
  KEY="0"
else
  KEY=$NUMBER
fi

NEW_NAME=$(
  ~/.config/menu/lib/menu.sh -p "New name = $NUMBER: " -c -w 500 <&- && echo
) || exit 1

swaymsg "rename workspace \"$NAME\" to \"$NUMBER: $NEW_NAME\""
swaymsg "bindsym \$mod+$KEY workspace \"$NUMBER: $NEW_NAME\""
swaymsg "bindsym \$mod+Shift+$KEY move container to workspace \"$NUMBER: $NEW_NAME\""

